---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app-devopsgol
  namespace: default
  labels:
    app: nodejs-app-devopsgol
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app-devopsgol
  template:
    metadata:
      labels:
        app: nodejs-app-devopsgol
    spec:
      containers:
      - name: nodejs-app-devopsgol
        image: "adinugroho251/my-node-app:1.3"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-devopsgol
  namespace: default
spec:
  selector:
    app: nodejs-app-devopsgol
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
